interface Box {
  name: string
  icons: Array<string>
}

export const IconBoxes: Array<Box> = [
  {
    name: 'Bandle City',
    icons: [
      'Corki Champie Icon',
      'Lulu Champie Icon',
      'Rumble Champie Icon',
      'Teemo Champie Icon',
      'Teemo Champie Icon II',
      'Tristana Champie Icon',
      'Veigar Champie Icon',
      'Yuumi Champie Icon',
    ],
  },
  {
    name: 'Bilgewater',
    icons: [
      'Gangplank Champie Icon',
      'Graves Champie Icon',
      'Illaoi Champie Icon',
      'Miss Fortune Champie Icon',
      'Nautilus Champie Icon',
      'Nilah Champie Icon',
      'Pyke Champie Icon',
      'Twisted Fate Champie Icon',
    ],
  },
  {
    name: 'Demacia',
    icons: [
      'Fiora Champie Icon',
      'Galio Champie Icon',
      'Garen Champie Icon',
      'Jarvan IV Champie Icon',
      'Kayle Champie Icon',
      'Kayle Champie Icon II',
      'Lux Champie Icon',
      'Morgana Champie Icon',
      'Morgana II Champie Icon',
      'Poppy Champie Icon',
      'Quinn Champie Icon',
      'Shyvana Champie Icon',
      'Sona Champie Icon',
      'Sylas Champie Icon',
      'Vayne Champie Icon',
      'Xin Zhao Champie Icon',
    ],
  },
  {
    name: 'Freljord',
    icons: [
      'Anivia Champie Icon',
      'Ashe Champie Icon',
      'Aurora Champie Icon',
      'Braum Champie Icon',
      'Gnar Champie Icon',
      'Gragas Champie Icon',
      'Lissandra Champie Icon',
      'Nunu & Willump Champie Icon',
      'Olaf Champie Icon',
      'Ornn Champie Icon',
      'Sejuani Champie Icon',
      'Trundle Champie Icon',
      'Tryndamere Champie Icon',
      'Udyr Champie Icon',
      'Volibear Champie Icon',
    ],
  },
  {
    name: 'Ionia',
    icons: [
      'Ahri Champie Icon',
      'Ahri Champie Icon II',
      'Akali Champie Icon',
      'Hwei Champie Icon',
      'Irelia Champie Icon',
      'Ivern Champie Icon',
      'Jhin Champie Icon',
      'Karma Champie Icon',
      'Kayn Champie Icon',
      'Kennen Champie Icon',
      'Lee Sin Champie Icon',
      'Lee Sin Champie Icon II',
      'Lillia Champie Icon',
      'Master Yi Champie Icon',
      'Rakan Champie Icon',
      'Sett Champie Icon',
      'Shen Champie Icon',
      'Syndra Champie Icon',
      'Varus Champie Icon',
      'Wukong Champie Icon',
      'Xayah Champie Icon',
      'Yasuo Champie Icon',
      'Yone Champie Icon',
      'Zed Champie Icon',
    ],
  },
  {
    name: 'Ixtal',
    icons: [
      'Malphite Champie Icon',
      'Milio Champie Icon',
      'Neeko Champie Icon',
      'Nidalee Champie Icon',
      'Qiyana Champie Icon',
      'Rengar Champie Icon',
      'Skarner Champie Icon II',
      'Zyra Champie Icon',
    ],
  },
  {
    name: 'Noxus',
    icons: [
      'Briar Champie Icon',
      'Cassiopeia Champie Icon',
      'Darius Champie Icon',
      'Draven Champie Icon',
      'Katarina Champie Icon',
      'Kled Champie Icon',
      'Leblanc Champie Icon',
      'Leblanc Champie Icon II',
      'Mordekaiser Champie Icon',
      'Rell Champie Icon',
      'Riven Champie Icon',
      'Samira Champie Icon',
      'Sion Champie Icon',
      'Swain Champie Icon',
      'Talon Champie Icon',
      'Vladimir Champie Icon',
    ],
  },
  {
    name: 'Piltover & Zaun',
    icons: [
      'Blitzcrank Champie Icon',
      'Caitlyn Champie Icon',
      'Caitlyn Champie Icon II',
      'Camille Champie Icon',
      'Dr. Mundo Champie Icon',
      'Ekko Champie Icon',
      'Ezreal Champie Icon',
      'Ezreal Champie Icon II',
      'Heimerdinger Champie Icon',
      'Janna Champie Icon',
      'Jayce Champie Icon',
      'Jinx Champie Icon',
      'Orianna Champie Icon',
      'Renata Glasc Champie Icon',
      'Seraphine Champie Icon',
      'Singed Champie Icon',
      'Twitch Champie Icon',
      'Urgot Champie Icon',
      'Vi Champie Icon',
      'Viktor Champie Icon',
      'Viktor Champie Icon II',
      'Warwick Champie Icon',
      'Zac Champie Icon',
      'Zeri Champie Icon',
      'Ziggs Champie Icon',
    ],
  },
  {
    name: 'Runeterra',
    icons: [
      'Aatrox Champie Icon',
      'Alistar Champie Icon',
      'Annie Champie Icon',
      'Aurelion Sol Champie Icon',
      'Bard Champie Icon',
      'Brand Champie Icon',
      'Evelynn Champie Icon',
      'Fiddlesticks Champie Icon',
      'Fizz Champie Icon',
      'Jax Champie Icon',
      'Kindred Champie Icon',
      'Lucian Champie Icon',
      'Nami Champie Icon',
      'Nocturne Champie Icon',
      'Ryze Champie Icon',
      'Senna Champie Icon',
      'Shaco Champie Icon',
      'Smolder Champie Icon',
      'Tahm Kench Champie Icon',
      'Zilean Champie Icon',
    ],
  },
  {
    name: 'Shadow Isles',
    icons: [
      'Elise Champie Icon',
      'Gwen Champie Icon',
      'Hecarim Champie Icon',
      'Kalista Champie Icon',
      'Karthus Champie Icon',
      'Maokai Champie Icon',
      'Thresh Champie Icon',
      'Vex Champie Icon',
      'Viego Champie Icon',
      'Yorick Champie Icon',
    ],
  },
  {
    name: 'Shurima',
    icons: [
      'Akshan Champie Icon',
      'Amumu Champie Icon',
      'Azir Champie Icon',
      'Naafiri Champie Icon',
      'Nasus Champie Icon',
      'Rammus Champie Icon',
      'Renekton Champie Icon',
      'Sivir Champie Icon',
      'Skarner Champie Icon',
      "K'Sante Champie Icon",
      'Taliyah Champie Icon',
      'Taliyah Champie Icon II',
      'Xerath Champie Icon',
    ],
  },
  {
    name: 'Targon',
    icons: [
      'Aphelios Champie Icon',
      'Diana Champie Icon',
      'Leona Champie Icon',
      'Pantheon Champie Icon',
      'Soraka Champie Icon',
      'Taric Champie Icon',
      'Zoe Champie Icon',
    ],
  },
  {
    name: 'The Void',
    icons: [
      "Bel'Veth Champie Icon",
      "Cho'Gath Champie Icon",
      "Kai'Sa Champie Icon",
      'Kassadin Champie Icon',
      "Kha'Zix Champie Icon",
      "Kog'Maw Champie Icon",
      'Malzahar Champie Icon',
      "Rek'Sai Champie Icon",
      "Vel'Koz Champie Icon",
    ],
  },
]

export const BoxNames: Array<string> = IconBoxes.map((box) => box.name)
